import { useState, type FormEvent } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';

import { useAuth } from '../context/auth-context';

export function AuthPage({ mode }: { mode: 'login' | 'register' }) {
  const auth = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); setBusy(true); const data = new FormData(event.currentTarget); try { if (mode === 'login') await auth.login(String(data.get('email')), String(data.get('password'))); else await auth.register(String(data.get('username')), String(data.get('email')), String(data.get('password'))); navigate((location.state as { from?: string } | null)?.from ?? '/'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to authenticate'); } finally { setBusy(false); } };
  return <main className="grid min-h-screen place-items-center bg-slate-950 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-8 shadow-2xl"><p className="font-semibold text-indigo-600">DriveLine</p><h1 className="mt-2 text-3xl font-bold">{mode === 'login' ? 'Welcome back' : 'Create your account'}</h1><p className="mt-2 text-slate-600">{mode === 'login' ? 'Sign in to manage your garage.' : 'Start browsing dealership inventory.'}</p>{error && <p role="alert" className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-6 grid gap-4">{mode === 'register' && <label className="text-sm font-medium">Username<input name="username" required minLength={3} className="mt-1 w-full rounded-lg border px-3 py-2" /></label>}<label className="text-sm font-medium">Email<input name="email" required type="email" className="mt-1 w-full rounded-lg border px-3 py-2" /></label><label className="text-sm font-medium">Password<input name="password" required type="password" minLength={8} className="mt-1 w-full rounded-lg border px-3 py-2" /></label><button disabled={busy} className="rounded-lg bg-indigo-600 px-4 py-3 font-semibold text-white disabled:bg-indigo-300">{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></div><p className="mt-6 text-center text-sm text-slate-600">{mode === 'login' ? 'New here?' : 'Already registered?'} <Link className="font-semibold text-indigo-600" to={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Create an account' : 'Sign in'}</Link></p></form></main>;
}
