import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';

import { VehicleCard } from '../components/vehicle-card';
import { VehicleForm } from '../components/vehicle-form';
import { useAuth } from '../context/auth-context';
import { dealershipService } from '../services/dealership.service';
import type { Vehicle, VehicleInput, VehicleSearch } from '../types/api';

const blankSearch: VehicleSearch = {};
export function DashboardPage() {
  const { user, logout } = useAuth(); const admin = user?.role === 'ADMIN';
  const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [filters, setFilters] = useState<VehicleSearch>(blankSearch); const [editing, setEditing] = useState<Vehicle | null | 'new'>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const load = async (search = filters) => { setLoading(true); try { const active = Object.fromEntries(Object.entries(search).filter(([, value]) => value)) as VehicleSearch; setVehicles(Object.keys(active).length ? await dealershipService.searchVehicles(active) : await dealershipService.listVehicles()); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Could not load vehicles'); } finally { setLoading(false); } };
  useEffect(() => { void load(blankSearch); }, []);
  const notify = (text: string) => { setMessage(text); window.setTimeout(() => setMessage(''), 3500); };
  const purchase = async (id: string) => { if (!user) { notify('Please sign in to purchase a vehicle.'); return; } try { await dealershipService.purchaseVehicle(id, 1); notify('Purchase completed.'); await load(); } catch (reason) { notify(reason instanceof Error ? reason.message : 'Purchase failed'); } };
  const save = async (input: VehicleInput) => { try { if (editing === 'new') await dealershipService.createVehicle(input); else if (editing) await dealershipService.updateVehicle(editing.id, input); setEditing(null); notify('Vehicle saved.'); await load(); } catch (reason) { notify(reason instanceof Error ? reason.message : 'Save failed'); } };
  const remove = async (id: string) => { if (!window.confirm('Archive this vehicle?')) return; try { await dealershipService.deleteVehicle(id); notify('Vehicle archived.'); await load(); } catch (reason) { notify(reason instanceof Error ? reason.message : 'Delete failed'); } };
  const restock = async (id: string) => { const value = window.prompt('Quantity to add'); const quantity = Number(value); if (!Number.isInteger(quantity) || quantity <= 0) return; try { await dealershipService.restockVehicle(id, quantity); notify('Inventory restocked.'); await load(); } catch (reason) { notify(reason instanceof Error ? reason.message : 'Restock failed'); } };
  const submitSearch = (event: FormEvent) => { event.preventDefault(); void load(filters); };
  return <main className="min-h-screen bg-slate-100"><header className="border-b bg-slate-950 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><Link to="/" className="text-xl font-bold">DriveLine</Link><div className="flex items-center gap-3">{user ? <><span className="hidden text-sm text-slate-300 sm:block">{user.username} · {user.role}</span><button onClick={logout} className="rounded-lg border border-slate-600 px-3 py-2 text-sm font-semibold">Logout</button></> : <><Link to="/login" className="text-sm font-semibold">Login</Link><Link to="/register" className="rounded-lg bg-indigo-500 px-3 py-2 text-sm font-semibold">Register</Link></>}</div></div></header><section className="mx-auto max-w-7xl px-4 py-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-semibold text-indigo-600">Inventory dashboard</p><h1 className="text-3xl font-bold text-slate-900">Find your next vehicle</h1></div>{admin && <button onClick={() => setEditing('new')} className="rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white">Add vehicle</button>}</div>{message && <p role="status" className="mt-4 rounded-lg bg-slate-900 p-3 text-sm text-white">{message}</p>}{editing && admin && <div className="mt-6"><VehicleForm vehicle={editing === 'new' ? undefined : editing} onSubmit={save} onCancel={() => setEditing(null)} /></div>}<form onSubmit={submitSearch} className="mt-6 grid gap-3 rounded-2xl bg-white p-4 shadow-card sm:grid-cols-3 lg:grid-cols-6">{(['make', 'model', 'category', 'minPrice', 'maxPrice'] as const).map((field) => <input key={field} value={filters[field] ?? ''} onChange={(event) => setFilters({ ...filters, [field]: event.target.value })} type={field.includes('Price') ? 'number' : 'text'} min={field.includes('Price') ? '0' : undefined} placeholder={field.replace(/([A-Z])/g, ' $1')} className="rounded-lg border border-slate-300 px-3 py-2" />)}<button className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white">Search</button></form>{loading ? <p className="py-12 text-center text-slate-500">Loading inventory…</p> : vehicles.length ? <div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{vehicles.map((vehicle) => <VehicleCard key={vehicle.id} vehicle={vehicle} isAdmin={admin} onPurchase={purchase} onEdit={setEditing} onDelete={remove} onRestock={restock} />)}</div> : <div className="mt-6 rounded-2xl border border-dashed border-slate-300 p-12 text-center text-slate-500">No vehicles match these filters.</div>}</section></main>;
}
