import { useState, type FormEvent } from 'react';

import type { Vehicle, VehicleInput } from '../types/api';

export function VehicleForm({ vehicle, onSubmit, onCancel }: { vehicle?: Vehicle; onSubmit(input: VehicleInput): Promise<void>; onCancel(): void }) {
  const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = new FormData(event.currentTarget); setSaving(true); try { await onSubmit({ make: String(values.get('make')), model: String(values.get('model')), category: String(values.get('category')), price: Number(values.get('price')), quantity: Number(values.get('quantity')), description: String(values.get('description')) || null, imageUrl: String(values.get('imageUrl')) || null }); } finally { setSaving(false); } };
  const fields: Array<[string, string | number]> = [['make', vehicle?.make ?? ''], ['model', vehicle?.model ?? ''], ['category', vehicle?.category ?? ''], ['price', vehicle?.price ?? ''], ['quantity', vehicle?.quantity ?? ''], ['imageUrl', vehicle?.imageUrl ?? '']];
  return <form onSubmit={submit} className="grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2">{fields.map(([name, value]) => <label key={name} className="text-sm font-medium capitalize">{name}<input required={name !== 'imageUrl'} name={name} type={name === 'price' || name === 'quantity' ? 'number' : 'text'} min={name === 'price' ? '0.01' : name === 'quantity' ? '0' : undefined} defaultValue={String(value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label>)}<label className="text-sm font-medium sm:col-span-2">Description<textarea name="description" defaultValue={vehicle?.description ?? ''} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><div className="flex gap-2 sm:col-span-2"><button disabled={saving} className="rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white">{saving ? 'Saving…' : 'Save vehicle'}</button><button type="button" onClick={onCancel} className="rounded-lg border px-4 py-2 font-semibold">Cancel</button></div></form>;
}
